modLoader = "javafml"
loaderVersion = "*"
license = "CC0-1.0"
issueTrackerURL = "https://github.com/bshuler/critical-flight-details/issues"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
description = '''${description}'''
authors = "TheCritic"
logoFile = "assets/${id}/icon.png"

[[dependencies.${id}]]
modId = "forge"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion},)"
ordering = "NONE"
side = "CLIENT"
