modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"
issueTrackerURL = "https://github.com/bshuler/critical-flight-details/issues"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
description = '''${description}'''
authors = "TheCritic, bshuler"
displayURL = "https://github.com/bshuler/critical-flight-details"
logoFile = "assets/flight_display/icon.png"

[[mixins]]
config = "flight_display.mixins.json"

[[dependencies.${id}]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion},)"
ordering = "NONE"
side = "CLIENT"
