# Minecraft 1.14.2 Dependencies
minecraft_version=1.14.2
yarn_mappings=1.14.2+build.7
loader_version=0.16.9
fabric_version=0.28.5+1.14
forge_version=1.14.2-26.0.63
loader_version_range=[26,)
forge_version_range=[26,)
minecraft_version_range=[1.14.2,1.15)
