# Minecraft 1.16.3 Dependencies
minecraft_version=1.16.3
yarn_mappings=1.16.3+build.47
loader_version=0.16.9
fabric_version=0.42.0+1.16
forge_version=1.16.3-34.1.42
loader_version_range=[34,)
forge_version_range=[34,)
minecraft_version_range=[1.16.3,1.17)
