# Minecraft 1.16.4 Dependencies
minecraft_version=1.16.4
yarn_mappings=1.16.4+build.9
loader_version=0.16.9
fabric_version=0.42.0+1.16
forge_version=1.16.4-35.1.37
loader_version_range=[35,)
forge_version_range=[35,)
minecraft_version_range=[1.16.4,1.17)
