# Minecraft 1.21.7 Dependencies
minecraft_version=1.21.7
yarn_mappings=1.21.7+build.1
yarn_mappings_neoforge_patch=1.21.7+build.1
loader_version=0.16.9
fabric_version=0.128.2+1.21.7
neoforge_version=21.7.25
loader_version_range=[4,)
neoforge_version_range=[21.7,)
minecraft_version_range=[1.21.7,1.21.8)
